---
title: "SurveyDataReport"
author: "Kasra Sammak"
date: "06/02/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# load libraries
library(ggplot2)
library(dplyr)

# read data
surveyData <- read.csv("data/surveyBelkinElago.csv", sep=";", dec =",")
surveyData <- subset(surveyData, brand != " ")

```
<p> Hi this is my plot </p>
```{r, echo=FALSE}
#call ggplot
c <- ggplot(surveyData, aes(salary, fill = brand))

#histogram (one variable)
c  + geom_histogram(bins=100) + 
  scale_fill_manual(values=c("brown", "black")) + 
  theme_dark() +
  labs(title = "Number of People per Salary at Belkin and Elago", subtitle = "A Histographical Representation")
```
<p> This is a rather simple plot, explaining how many people have what salary by Brand </p>
```{r, echo=FALSE}
#scatter (2 variables)
d <- ggplot(data=surveyData, aes(x = age, y = credit, colour = brand))
d +
  theme_dark() +
  geom_point() +
  scale_colour_manual(values=c("brown", "black")) + 
  labs(title = "Credit score per Age at Belkin and Elago", 
       subtitle = "A Scatter Plot Representation")
```
